version: '3.4'

services:
  nodejs:
    image: nodejs
    build:
      context: src
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    volumes: 
      - ./src/bin:/usr/src/app/bin
      - ./docker/config:/usr/src/app/config
      - ./src/public:/usr/src/app/public
      - ./src/routes:/usr/src/app/routes
      - ./src/services:/usr/src/app/services
      - ./src/tests/:/usr/src/app/tests/
      - ./src/utils:/usr/src/app/utils
      - ./src/views:/usr/src/app/views
      - ./src/app.js:/usr/src/app/app.js
    command: ["npm", "--inspect=0.0.0.0:9229", "run", "test"]
